name: Mirror to Public Repo

on:
  push:
    branches:
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout original repo
      uses: actions/checkout@v2

    - name: Clone and prepare mirror repository
      run: |
        git clone --branch main https://github.com/IlhanTech/MIROR-RTYPE.git mirror
        cd mirror
        git checkout -b temp

    - name: Sync changes
      run: |
        rsync -a --exclude .git --exclude mirror ../ mirror/

    - name: Push to mirror repository
      run: |
        cd mirror
        git config user.name "IlhanTech"
        git config user.email "ilhan.neuville@epitech.eu"
        git add .
        git diff --staged --quiet || git commit -m "Update from original repo"
        git remote set-url origin https://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@github.com/IlhanTech/MIROR-RTYPE.git
        git push origin temp:main
      env:
        GITHUB_TOKEN: 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
