name: Mirror to Public Repo

on:
  push:
    branches:
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout original repo
      uses: actions/checkout@v2

    - name: Clone mirror repository
      run: |
        git clone --branch main https://github.com/IlhanTech/MIROR-RTYPE.git mirror

    - name: Clean mirror repository
      run: |
        cd mirror
        # Find and delete all files and directories, excluding the .git directory
        find . -not -name '.git' -not -path './.git/*' -delete
        cd ..

    - name: Copy contents to mirror
      run: |
        rsync -av --exclude='.git' --exclude='mirror' ./ ./mirror/

    - name: Commit and push to mirror repository
      run: |
        cd mirror
        git config user.name "IlhanTech"
        git config user.email "ilhan.neuville@epitech.eu"
        git add .
        git diff --staged --quiet || git commit -m "Update from original repo"
        git remote set-url origin https://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@github.com/IlhanTech/MIROR-RTYPE.git
        git push origin main
      env:
        GITHUB_TOKEN: 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

    - name: Remove mirror directory
      run: |
        rm -rf mirror
