name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t monserveurimage .

    - name: Push to Docker Registry
      run: |
        docker tag monserveurimage ilhantech/monserveurimage:tag
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ilhantech/monserveurimage:tag

    - name: Créer un fichier pour la Clé SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Ajouter la Clé SSH du Serveur aux Hôtes Connus
      run: ssh-keyscan -H 68.183.79.110 >> ~/.ssh/known_hosts

    - name: Déployer sur le Serveur
      run: ssh -i ~/.ssh/id_rsa root@68.183.79.110 'docker pull ilhantech/monserveurimage:tag && docker run -d -p 8000:8000 ilhantech/monserveurimage:tag'
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t monserveurimage .

    - name: Push to Docker Registry
      run: |
        docker tag monserveurimage ilhantech/monserveurimage:tag
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ilhantech/monserveurimage:tag

    - name: Créer un fichier pour la Clé SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Ajouter la Clé SSH du Serveur aux Hôtes Connus
      run: ssh-keyscan -H 68.183.79.110 >> ~/.ssh/known_hosts

    - name: Déployer sur le Serveur
      run: ssh -i ~/.ssh/id_rsa root@68.183.79.110 'docker pull ilhantech/monserveurimage:tag && docker run -d -p 8000:8000 ilhantech/monserveurimage:tag'
